name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node

      - name: Checkout
        if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        if: ${{ steps.release-please.outputs.release_created }}
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v4
        if: ${{ steps.release-please.outputs.release_created }}
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        if: ${{ steps.release-please.outputs.release_created }}
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build package
        if: ${{ steps.release-please.outputs.release_created }}
        run: pnpm build

      - name: Publish to npm
        if: ${{ steps.release-please.outputs.release_created }}
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
